[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "mysql80", "openssl", "libffi", "zlib"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "/opt/venv/bin/python manage.py collectstatic --noinput"
]

[phases.start]
cmds = [
  "/opt/venv/bin/gunicorn auth.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 3"
]

# Set environment variables
[variables]
PORT = "8000"