[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config", "mysql80", "openssl"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt"
]


